---
- name: Sets up key mappings
  hosts: localhost
  vars:
  - home: "{{ lookup('env', 'HOME') }}"

  tasks:
  - name: Adding custom key mapping
    copy:
      src: ".Xmodmap"
      dest: "{{ home }}/.Xmodmap"

  - name: Updating bash
    blockinfile:
      dest: "{{ home }}/.bash_profile"
      regexp: "if [[ -f \"$HOME/.Xmodmap\" ]]; then"
      create: yes
      content: |
        if [[ -f "$HOME/.Xmodmap" ]]; then
          xmodmap "$HOME/.Xmodmap"
        fi

  - name: Applying custom key mappings
    shell: |
      xmodmap "{{ home }}/.Xmodmap"
    args:
      executable: /bin/bash
