---
- name: Installs Chrome
  hosts: localhost

  vars:
  - version: stable

  tasks:
  - name:
    become: true
    become_method: sudo
    block:
    - name: Add Google GPG apt Key
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Add Google Earth Repository
      apt_repository:
        repo: deb http://dl.google.com/linux/earth/deb/ {{ version }} main
        state: present

    - name: Update apt and install Google Earth Pro
      apt: update_cache=yes name=google-earth-pro-{{ version }} state=latest
