#!/bin/bash

set -x

ansible-playbook ./playbook/keymap/keymap.yml
ansible-playbook ./playbook/bash/bash.yml
ansible-playbook ./playbook/nano/nano.yml
ansible-playbook ./playbook/git/git.yml
ansible-playbook ./playbook/aws/aws.yml

ansible-playbook ./playbook/privileged-playbooks.yml --ask-become-pass
