---
- name: Insall Zoom
  hosts: localhost
  vars:
  - user_home: "{{ lookup('env', 'HOME') }}"
  - arch: amd64


  tasks:
  - name: Getting Zoom
    get_url:
      url: "https://zoom.us/client/latest/zoom_{{ arch }}.deb"
      dest: "{{ user_home }}/Downloads/zoom_{{ arch }}.deb"

  - name: Install Zoom
    become: true
    become_method: sudo
    apt:
      deb: "{{ user_home }}/Downloads/zoom_{{ arch }}.deb"

