---
- name: Insall golang
  hosts: localhost
  vars:
  - user_home: "{{ lookup('env', 'HOME') }}"
  - version: 1.15.4
  - arch: amd64
  - os: linux

  tasks:
  - name: Get golang
    get_url:
      url: "https://dl.google.com/go/go{{ version }}.{{ os }}-{{ arch }}.tar.gz"
      dest: "{{ user_home }}/Downloads/go{{ version }}.{{ os }}-{{ arch }}.tar.gz"

  - name: Unpack golang
    become: true
    become_method: sudo
    unarchive:
      src: "{{ user_home }}/Downloads/go{{ version }}.{{ os }}-{{ arch }}.tar.gz"
      dest: /usr/local

  - name: Update PATH
    blockinfile:
      dest: "{{ user_home }}/.profile"
      marker: "# {mark} ANSIBLE MANAGED BLOCK gobin"
      block: |
        export PATH=$PATH:/usr/local/go/bin

  - name: Set GOPATH
    blockinfile:
      dest: "{{ user_home }}/.profile"
      marker: "# {mark} ANSIBLE MANAGED BLOCK gopath"
      block: |
        export GOPATH={{ user_home }}/go

  - name: Source PATH
    shell: |
      source "{{ user_home }}/.profile"
    args:
      executable: /bin/bash

