---
- name: Insall golang
  hosts: localhost
  vars:
  - user_home: "{{ lookup('env', 'HOME') }}"
  - checksum: sha256:08df79b46b0adf498ea9f320a0f23d6ec59e9003660b4c9c1ce8e5e2c6f823ca
  - version: 1.14
  - arch: amd64
  - os: linux

  tasks:
  - name: Getting golang
    get_url:
      url: "https://dl.google.com/go/go{{ version }}.{{ os }}-{{ arch }}.tar.gz"
      dest: "{{ user_home }}/Downloads/go{{ version }}.{{ os }}-{{ arch }}.tar.gz"
      checksum: "{{ checksum }}"

  - name: Unpacking golang
    become: true
    become_method: sudo
    unarchive:
      src: "{{ user_home }}/Downloads/go{{ version }}.{{ os }}-{{ arch }}.tar.gz"
      dest: /usr/local

  - name: Updating PATH
    blockinfile:
      dest: "{{ user_home }}/.bash_profile"
      regexp: "export PATH=$PATH:/usr/local/go/bin"
      create: yes
      content: |
        export PATH=$PATH:/usr/local/go/bin

  - name: Soursign PATH
    shell: |
      source "{{ user_home }}/.bash_profile"
    args:
      executable: /bin/bash

