---
- name: Install net-tools
  hosts: localhost
  tasks:
  - name: Install net-tools
    become: true
    become_method: sudo
    apt: 
      name: net-tools 
      state: latest
      update_cache: yes
