---
- name: Insall Terraform
  hosts: localhost
  vars:
  - user_home: "{{ lookup('env', 'HOME') }}"
  - version: 0.14.7
  - arch: amd64
  - os: linux

  tasks:
  - name: Getting Terraform
    get_url:
      url: "https://releases.hashicorp.com/terraform/{{ version }}/terraform_{{ version }}_{{ os }}_{{ arch }}.zip"
      dest: "{{ user_home }}/Downloads/terraform_{{ version }}_{{ os }}_{{ arch }}.zip"

  - name: Unpacking Traform
    become: true
    become_method: sudo
    unarchive:
      src: "{{ user_home }}/Downloads/terraform_{{ version }}_{{ os }}_{{ arch }}.zip"
      dest: /usr/local/bin

  - name: Soursign PATH
    shell: |
      source "{{ user_home }}/.profile"
    args:
      executable: /bin/bash
