---
- name: Configuring bash
  hosts: localhost

  vars:
  - user_home: "{{ lookup('env', 'HOME') }}"

  tasks:
  - name: copy bash utility scripts
    copy:
      src: "files/{{ item }}.sh"
      dest: "{{ user_home }}/.{{ item }}"
    with_items:
    - bash_aliases
    - bash_functions

  - name: update bash_profile with bash_aliases
    blockinfile:
      dest: "{{ user_home }}/.bash_profile"
      marker: "# {mark} ANSIBLE MANAGED BLOCK bash"
      block: |
        source {{ user_home }}/.bash_aliases
        source {{ user_home }}/.bash_functions

  - name: Source PATH
    shell: |
      source "{{ user_home }}/.bash_profile"
    args:
      executable: /bin/bash
