---
- name: Installs Chrome
  hosts: localhost

  vars:
  - version: stable

  tasks:
  - name:
    become: true
    become_method: sudo
    block:
    - name: Add Chrome GPG apt Key
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Add Chrome Repository
      apt_repository:
        repo: deb http://dl.google.com/linux/chrome/deb/ {{ version }} main
        state: present

    - name: Update apt and install Chrome
      apt: update_cache=yes name=google-chrome-stable state=latest
